### ISSUE TITLE
Job TF.AW.AdMetricSync is failing

### ISSUE THREAD

**Issue by FredRanieri** [Marketing-Automation-Systems/jellyfish#15]
**Describe the bug 🐛**

AdWords Transformation AdMetricSync is failing due to the error below.

```
Failed. Took "00:00:29.1411271".
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at Jobs.Transformation.AdWords.AdMetricSync.<>c__DisplayClass4_3.<ListAdMetrics>b__5(SourceAdMetric a) in /home/ubuntu/BuildAgent/work/65d81077067c10a5/src/Jobs.Transformation/Google/AdWordsJobs.cs:line 233
```

- [x] I have searched the [issues](https://github.com/Marketing-Automation-Systems/jellyfish/issues/) of this repository and believe that this is not a duplicate.

**To Reproduce**
Steps to reproduce the behavior 😯:
1. Go to `src/ConsoleApp`
2. Run `dotnet run -- jobs -j Jobs.Transformation.AdWords.AdMetricSync`

**Expected behavior  🤔**

In my opinion, this error can be happening due to a problem during fetching data or fetching a wrong type(expected int but it is a string).

**Your environment:**
 - OS: Ubuntu 18.04
 - Browser chrome

**Comment by FredRanieri** [comment]
This issue can be closed due to the result of #25
